version: '3.4'
services:
  app: &app
    build:
      context: .
      target: dev
    command: [ rails, server, -b, '0.0.0.0' ]
    depends_on:
    - db
    - mail
    - cache
    - worker
    env_file: .docker/app.env
    environment:
    - RAILS_ENV=development
    ports:
    - '3000:3000'
    - '1234:1234'
    tmpfs: /app/hitobito/tmp/pids
    volumes:
    - ./:/app
    - seed:/seed

  worker:
    <<: *app
    entrypoint: worker-entrypoint
    command: [ rake, 'jobs:work' ]
    ports: []
    depends_on:
    - db
    - mail
    - cache
    ports: []

  test: &test
    build:
      context: .
      target: test
    command: rspec
    depends_on:
    - db-test
    env_file: .docker/app.env
    environment:
      RAILS_ENVIRONMENT: test
      RAILS_DB_NAME: hitobito_test
      RAILS_DB_HOST: db-test
    tmpfs: /app/hitobito/tmp/pids
    volumes:
    - ./:/app

  app-test:
    <<: *test
    command: [ tail, -f, /dev/null ]
    ports:
    - "1234:1234"
    - "58438:58438"
    - "58439:58439"

  # Dependencies

  mail:
    build:
      context: .
      target: base
    command: [ mailcatcher, -f, --ip, '0.0.0.0' ]
    ports:
    - "1080:1080"

  cache:
    image: memcached:1.5-alpine
    command: [ memcached, -l, '0.0.0.0', -p, '11211' ]

  sphinx:
    image: macbre/sphinxsearch:3.1.1
    depends_on:
    - db
    volumes:
    - sphinx:/opt/sphinx/index
    - ./.docker/sphinx.conf:/opt/sphinx/conf/sphinx.conf:ro

  indexer:
    image: macbre/sphinxsearch:3.1.1
    command: [ indexer, --config, /opt/sphinx/conf/sphinx.conf, --all ]
    depends_on:
    - db
    volumes:
    - sphinx:/opt/sphinx/index
    - ./.docker/sphinx.conf:/opt/sphinx/conf/sphinx.conf:ro

  db:
    image: mysql:5.6
    command:
    - --sort_buffer_size=2M
    env_file: .docker/mysql.env
    ports:
    - "33066:3306"
    volumes:
    - db:/var/lib/mysql

  db-test:
    image: mysql:5.6
    command:
    - --sort_buffer_size=2M
    env_file: .docker/mysql.env
    environment:
      MYSQL_DATABASE: hitobito_test

volumes:
  db:
  sphinx:
  seed:

